# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obot < Formula
  desc "Obot CLI"
  homepage "https://github.com/obot-platform/obot"
  version "0.25.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/obot-platform/obot/releases/download/v0.25.3/obot_v0.25.3_darwin_amd64.tar.gz"
      sha256 "ac73b2cda6f41ae00b0aa5bef1445855d715f2b8171a4e8074a50e7554011bc6"

      define_method(:install) do
        bin.install "obot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/obot-platform/obot/releases/download/v0.25.3/obot_v0.25.3_darwin_arm64.tar.gz"
      sha256 "ebda4f6bb4b4fc55e8b83006140738a65aca078789e78c4e5de55b0d530115a1"

      define_method(:install) do
        bin.install "obot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/obot-platform/obot/releases/download/v0.25.3/obot_v0.25.3_linux_amd64.tar.gz"
      sha256 "b9276e4ecac81d94b414c26d5168b3ecc7fdf85c0b3ca73c587e24bd3c671a17"
      define_method(:install) do
        bin.install "obot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/obot-platform/obot/releases/download/v0.25.3/obot_v0.25.3_linux_arm64.tar.gz"
      sha256 "08736646ff289cff436ce6e7816be00dca8db56e361b03e8cb2429584fb6760e"
      define_method(:install) do
        bin.install "obot"
      end
    end
  end
end
