# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obot < Formula
  desc "Obot CLI"
  homepage "https://github.com/obot-platform/obot"
  version "0.8.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/obot-platform/obot/releases/download/v0.8.0/obot_v0.8.0_darwin_amd64.tar.gz"
      sha256 "1808ecde8575d87b1e39df91e06efe135dbbebc6d0fc132619c12b45652870b8"

      def install
        bin.install "obot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/obot-platform/obot/releases/download/v0.8.0/obot_v0.8.0_darwin_arm64.tar.gz"
      sha256 "83f2fe9d09b7aab7351a63c1fac8dca51f81f982740f97a294cae5b5c721cf54"

      def install
        bin.install "obot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/obot-platform/obot/releases/download/v0.8.0/obot_v0.8.0_linux_amd64.tar.gz"
      sha256 "0538b1757d34e98416bf71ae33d5ae3002f84ac13efb0c70aee84a4a60b09bc8"
      def install
        bin.install "obot"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/obot-platform/obot/releases/download/v0.8.0/obot_v0.8.0_linux_arm64.tar.gz"
      sha256 "8b2eea71384b974d168057de3402bfcd253083150e811f75634b38e38dff5412"
      def install
        bin.install "obot"
      end
    end
  end
end
