# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obot < Formula
  desc "Obot CLI"
  homepage "https://github.com/obot-platform/obot"
  version "0.22.0-alpha8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/obot-platform/obot/releases/download/v0.22.0-alpha8/obot_v0.22.0-alpha8_darwin_amd64.tar.gz"
      sha256 "d76afeaf084016824fb4836a558f43b1fa83a8bad379cb335c5708838b26eefe"

      define_method(:install) do
        bin.install "obot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/obot-platform/obot/releases/download/v0.22.0-alpha8/obot_v0.22.0-alpha8_darwin_arm64.tar.gz"
      sha256 "5ac474d902de35c8c93ef0e397e74b81bfa00c0817ca7f9a39a2239610c987c6"

      define_method(:install) do
        bin.install "obot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/obot-platform/obot/releases/download/v0.22.0-alpha8/obot_v0.22.0-alpha8_linux_amd64.tar.gz"
      sha256 "b293c36ba988dcc194b6a36a939d06f08181432da7e49acd5b09a1554655112a"
      define_method(:install) do
        bin.install "obot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/obot-platform/obot/releases/download/v0.22.0-alpha8/obot_v0.22.0-alpha8_linux_arm64.tar.gz"
      sha256 "24d55ce6c27c7527b29ca486ca8420e79e6c12b4c591ffc8b779444f9460568c"
      define_method(:install) do
        bin.install "obot"
      end
    end
  end
end
